version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: gestionMagica
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestionMagica
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_gestionMagicaNet

volumes:
  mysql_data:

networks:
  mysql_gestionMagicaNet:
    driver: bridge